controls/1.04-iam.rb, controls/7.01-gke.rb, controls/7.02-gke.rb, controls/7.03-gke.rb, controls/7.04-gke.rb, controls/7.05-gke.rb, controls/7.06-gke.rb, controls/7.07-gke.rb, controls/7.08-gke.rb, controls/7.09-gke.rb, controls/7.10-gke.rb, controls/7.11-gke.rb, controls/7.12-gke.rb, controls/7.13-gke.rb, controls/7.14-gke.rb, controls/7.15-gke.rb, controls/7.16-gke.rb, controls/7.17-gke.rb, controls/7.18-gke.rb, inspec.yml, libraries/gcp_helpers.rb
To reduce the time spent looping over empty zones/regions looking for GKE clusters, this adds an array input to specify the list of zone names and/or region names (locations) where to look.  Often, this is a small number, and can save 30+ seconds per run if specified.  If not specified, the prior behavior of looking in all locations is preserved.
=> GKE locations input array and two GKE control bug fixes

controls/1.04-iam.rb, controls/4.01-vms.rb, controls/4.02-vms.rb, controls/4.04-vms.rb, controls/4.05-vms.rb, controls/4.06-vms.rb, controls/7.01-gke.rb, controls/7.02-gke.rb, controls/7.03-gke.rb, controls/7.04-gke.rb, controls/7.05-gke.rb, controls/7.06-gke.rb, controls/7.07-gke.rb, controls/7.08-gke.rb, controls/7.09-gke.rb, controls/7.10-gke.rb, controls/7.11-gke.rb, controls/7.12-gke.rb, controls/7.13-gke.rb, controls/7.14-gke.rb, controls/7.15-gke.rb, controls/7.16-gke.rb, controls/7.17-gke.rb, controls/7.18-gke.rb, inspec.yml, libraries/gcp_helpers.rb
Similar to the GKE cluster lookup caching helper, do the same for GCE instances to only have to use the plural resource once for the entire profile run.
=> GCE instance lookup caching

controls/1.04-iam.rb, inspec.yml
Using inspec-gcp v1.5.0 now, service account keys are being pulled correctly
=> Kschieban/inspec gcpv1.4.0

controls/1.08-iam.rb
Runs into exception if `roles/iam.serviceAccountAdmin` does not exist.
=> fix check for nil

controls/4.05-vms.rb, controls/4.07-vms.rb, inspec.yml
Just noticed the mismatch which can be problematic when generating
InSpec reports. It can result in duplication of fields and/or inconsistent
results in reports.
Example where references from two controls are merged into one resulting
in a structure which is difficult to parse:
```
...
"refs": [
{
"url": "https://www.cisecurity.org/benchmark/google_cloud_computing_platform/",
"ref": "CIS Benchmark"
},
{
"url": "https://cloud.google.com/compute/docs/networking#canipforward",
"ref": "GCP Docs"
},
{
"ref": [
{
"url": "https://www.cisecurity.org/benchmark/google_cloud_computing_platform/",
"ref": "CIS Benchmark"
},
{
"url": "https://cloud.google.com/compute/docs/disks/customer-supplied-encryption#encrypt_a_new_persistent_disk_with_your_own_keys",
"ref": "GCP Docs"
},
{
"url": …
```
=> Fix mismatching control IDs

controls/1.10-iam.rb, inspec.yml
/gcbrun
Since the GCP Key Management Service does not support automatic rotation
of asymmetric keys (see: [Considerations for asymmetric keys](https://cloud.google.com/kms/docs/key-rotation#asymmetric)) and the fact that
KMS API calls for asymmetric keys don't return `enabled` and `disabled` state,
checks running against such keys are failing at the moment. That's why
we should only test KMS cryptographic keys which are symmetric.
Fixes error:
```
×  Control Source Code Error inspec-gcp-cis-benchmark-1.1.0-9/controls/1.10-iam.rb:24
undefined method `[]' for nil:NilClass
```
=> Verify whether automatic key rotation is enabled only for symmetric keys

controls/1.05-iam.rb, inspec.yml
We are staying away from primitive roles as much as possible and since
recently we are no longer using the Owner role in our projects. That
resulted in InSpec errors because there were no longer any IAM
bindings with that role. With the following fix, InSpec will look for
any bindings related to Editor/Owner and, in case of any present, will
examine those.
=> Fixes around Editor and Owner permissions checks

controls/4.01-vms.rb, controls/4.02-vms.rb, controls/4.05-vms.rb, inspec.yml
I just checked the section 4 of the latest documentation (ver1.1.0 03-11-2020) and it looks like the exclusion logics for GKE are wrong.
- Control 4.1 excludes instances created by GKE, see page 122.
- Control 4.2 excludes instances created by GKE, see page 125.
- Control 4.5 includes instances created by GKE, because of an exception isn't mentioned, see page 134 onwards.
Please review this pr. Thank you for your time.
=> Fix exclusion logics for GKE

controls/4.02-vms.rb, inspec.yml
Skip **non** default service account with full access to all Cloud APIs for Control 4.2; `Ensure that instances are not configured to use the default service account with full access to all Cloud APIs (Scored)`.
FYI, I used the following code as a guide.
https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/blob/40781b7ecb15ec751ee8051c1a218ac13cef805a/controls/4.01-vms.rb#L44-L53
Please review this pr. Thank you for your time again 😄
=> Skip non default service account with full access to all Cloud APIs

README.md
This PR adds missing GCP permissions that were discovered in our benchmark runs through Stackdriver Audit log activity.
Please don't merge yet, as we will verify if these are sufficient still.
=> Fix GCP permissions in README

README.md
This PR adds documentation to resolve access control issues described in https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/issues/54.
Namely, besides the required permissions, a number of Google APIs must be enabled in both the "source" project of the Service Account that runs the benchmark, and the "target" project to be scanned (as these projects may be the same or different).
=> List required APIs in README

controls/6.01-db.rb, controls/6.02-db.rb, controls/6.03-db.rb, inspec.yml
Prior to this change, each of the "db flag" related tests was looping
over all flags in a particular database and comparing both `name` and
`value` fields which results in multiple errors such as the ones below:
```
×  [gcp_project_id , postgres_db ] should have a database flag 'log_min_error_statement' set to 'ERROR'  name is expected to cmp == "log_min_error_statement"
expected: "log_min_error_statement"
got: "log_connections"
(compared using `cmp` matcher)
×  [gcp_project_id , postgres_db ] should have a database flag 'log_min_error_statement' set to 'ERROR'  value is expected to cmp == "ERROR"
expected: "ERROR"
got: "on"
```
=> Fix looping over the Cloud SQL database flags

controls/3.08-networking.rb, inspec.yml
Fix https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/issues/64
=> Skip vpc flow log checks for internal HTTPS LB subnets

README.md, inspec.yml, walkthrough.md
- updated README to add the JSON reporter to the process 
- updated Walkthrough to create a JSON result and then load into Heimdall Lite
Signed-off-by: Aaron Lippold <lippold@gmail.com>
=> Added directions for Heimdall Lite 

controls/1.05-iam.rb, inspec.yml
Discovered when InSpec is checking conditional role bindings. In
case they don't have any members (it happens after the expiration of
the condition), the control simply fails because of the `nil` value.
The issue is not well surfaced. In the beginning we were getting errors
like this one:
```
...
✔  [gsk-gsk-direct-e7d9] Admin roles members is expected not to include /@[a-z][a-z0-9|-]{4,28}[a-z].iam.gserviceaccount.com/
✔  [gsk-gsk-direct-e7d9] Admin roles members is expected not to include /@[a-z][a-z0-9|-]{4,28}[a-z].iam.gserviceaccount.com/
×  [gsk-gsk-direct-e7d9] Admin roles members is expected not to include /@[a-z][a-z0-9|-]{4,28}[a-z].iam.gserviceaccount.com/
expected nil not to include /@[a-z][a-z0-9|-]{4,28}[a-z].iam.gserviceaccount.com/, but it does not respond to `include?`
✔ …
```
=> Addressing conditional IAM role bindings

controls/2.04-logging.rb, controls/2.05-logging.rb, controls/2.06-logging.rb, controls/2.07-logging.rb, controls/2.08-logging.rb, controls/2.09-logging.rb, controls/2.10-logging.rb, controls/2.11-logging.rb, inspec.yml
/gcbrun
fix https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/issues/70
The CIS benchmark does not specifically call out the implemented alerting conditions. Suggestion to remove them and check the existence of a policy and a condition instead.
=> fix log metrics and remove alert conditions

controls/2.04-logging.rb, controls/2.05-logging.rb, controls/2.06-logging.rb, controls/2.07-logging.rb, controls/2.08-logging.rb, controls/2.09-logging.rb, controls/2.10-logging.rb, controls/2.11-logging.rb
/gcbrun
As all the log metrics does not support for the resource type as 'audited_resource' and gives the error after creating a report.
I am suggesting few changes, by providing the necessary GCP supported resources types for logging and monitoring in the code. any thoughts @KonradSchieban 
Please review @binamov
=> Log metrix fix adding the resource types

controls/3.01-networking.rb, controls/5.02-storage.rb
Some controls have incorrectly labeled CIS Level:
- **3.01-networking**
- **5.02-storage**
This PR fixes those, based on the manual spot-check against the CIS GCP 1.1.0 reference doc. The reason our team cares about their correctness is because we prioritize our compliance implementation decisions based on whether a certain control is Level 1 (required) or Level 2 (recommended).
Thank you!
=> Fix CIS Levels

controls/4.08-vms.rb, inspec.yml
A brief summary of the changes:
- Adding one extra check for making sure secure boot is enabled for
Shielded VMs.
- Changing the title of the control (probably bad copy-paste).
- Updating the `inspec-gcp-helpers` dependency to the latest version.
**Note**: The versioning in `inspec-gcp-helpers` is a inconsistent. Some tags are starting with `v1...` others are starting with `1...`.
=> Ensure secure boot is enabled for Shielded VMs

controls/1.04-iam.rb, controls/1.07-iam.rb, controls/1.08-iam.rb, controls/1.09-iam.rb, controls/1.10-iam.rb, controls/3.04-networking.rb, controls/3.05-networking.rb, controls/6.01-db.rb, controls/6.02-db.rb, controls/6.03-db.rb
This fixes #96.
Currently there is an issue where tests that are applicable will get marked as NA due to the impact being set to 'none' inside of a loop, which overrides the existing impact. This restructures those tests to properly handle such situations, causing correct results to be displayed.
Note: This currently has a dependency on #94, I can rebase it once the other PR is merged.
=> Avoid marking applicable controls as Not Applicable

.gitignore, controls/6.02-db.rb
The input variable for check 6..2.8 is not being imported to the module resulting in chef/inspec crashing when evaluating this check; simply adding a line to  import it.
=> fix 6.2.8 input var ref
